import Head from "next/head";
import styles from "../styles/Home.module.css";

import { NameDisplay } from "../components/NameDisplay";
import { NameForm } from "../components/NameForm";

import type { InferGetServerSidePropsType } from "next";

export default function TestSSR(
  _: InferGetServerSidePropsType<typeof getServerSideProps>
) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <NameDisplay />
        <NameForm />
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  const res = await fetch("http://localhost:3000/api/hello");
  const data = await res.json();

  return { props: { initialRecoilState: { nameState: data.name } } };
};
